
package ims.project;

import javax.swing.*;
import java.sql.*;
import database.Conn;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author abhi
 */

public class Catagory extends javax.swing.JFrame {

    /**
     * Creates new form Catagory
     */
    public Catagory() {
        initComponents();
    }

    public Catagory(String role) {
        initComponents();
        if (role.equals("Admin")) {
            this.role = role;
            userBtn.setVisible(false);
        }
    }

    private boolean validateForm() {
        if (!catagoryField.getText().equals("")) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userBtn = new javax.swing.JButton();
        catagoryBtn = new javax.swing.JButton();
        productBtn = new javax.swing.JButton();
        customerBtn = new javax.swing.JButton();
        orderBtn = new javax.swing.JButton();
        viewOrderBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        catagoryTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        catagoryField = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 1042, 533));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        userBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userBtn.setForeground(new java.awt.Color(255, 255, 255));
        userBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Users.png"))); // NOI18N
        userBtn.setText("User");
        userBtn.setBorder(null);
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });
        getContentPane().add(userBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, -1));

        catagoryBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        catagoryBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        catagoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        catagoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/category.png"))); // NOI18N
        catagoryBtn.setText("Catagory");
        catagoryBtn.setBorder(null);
        catagoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catagoryBtnActionPerformed(evt);
            }
        });
        getContentPane().add(catagoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 140, -1));

        productBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        productBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        productBtn.setForeground(new java.awt.Color(255, 255, 255));
        productBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/product.png"))); // NOI18N
        productBtn.setText("Product");
        productBtn.setBorder(null);
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });
        getContentPane().add(productBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 130, 40));

        customerBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        customerBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        customerBtn.setForeground(new java.awt.Color(255, 255, 255));
        customerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customers.png"))); // NOI18N
        customerBtn.setText("Customer");
        customerBtn.setToolTipText("");
        customerBtn.setBorder(null);
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 140, 40));

        orderBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        orderBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        orderBtn.setForeground(new java.awt.Color(255, 255, 255));
        orderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Orders.png"))); // NOI18N
        orderBtn.setText("Order");
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });
        getContentPane().add(orderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 40));

        viewOrderBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        viewOrderBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        viewOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewOrderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View-orders.png"))); // NOI18N
        viewOrderBtn.setText("View Order");
        viewOrderBtn.setBorder(null);
        viewOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 150, 40));

        logOutBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        logOutBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.setBorder(null);
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 140, -1));

        catagoryTable.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        catagoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Catagory"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        catagoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catagoryTableMouseClicked(evt);
            }
        });
        catagoryTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                catagoryTableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(catagoryTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 137, 590, 370));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CATAGORY MANAGER");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1040, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Catagory");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, -1, -1));

        catagoryField.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        getContentPane().add(catagoryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 230, -1));

        updateBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 110, -1));

        saveBtn.setBackground(new java.awt.Color(51, 255, 51));
        saveBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 100, -1));

        deleteBtn.setBackground(new java.awt.Color(255, 51, 51));
        deleteBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 110, -1));

        resetBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, 100, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_background.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        // TODO add your handling code here:
        UserManager userManager;
        if (role.equals("Admin")){ 
            userManager = new UserManager(role);
        }else {
            userManager = new UserManager();
        }
        setVisible(false);
        dispose();
        userManager.setVisible(true);
    }//GEN-LAST:event_userBtnActionPerformed

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        // TODO add your handling code here:
        Product product;
        if (role.equals("Admin")){ 
            product = new Product(role);
        }else {
            product = new Product();
        }
        setVisible(false);
        dispose();
        product.setVisible(true);
    }//GEN-LAST:event_productBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:
        Customer customer;
        if (role.equals("Admin")){ 
            customer = new Customer(role);
        }else {
            customer = new Customer();
        }
        setVisible(false);
        dispose();
        customer.setVisible(true);
    }//GEN-LAST:event_customerBtnActionPerformed

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        // TODO add your handling code here:
                Order order;
        if (role.equals("Admin")){ 
            order = new Order(role);
        }else {
            order = new Order();
        }
        setVisible(false);
        dispose();
        order.setVisible(true);
    }//GEN-LAST:event_orderBtnActionPerformed

    private void viewOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderBtnActionPerformed
        // TODO add your handling code here:
                ViewOrder viewOrder;
        if (role.equals("Admin")){ 
            viewOrder = new ViewOrder(role);
        }else {
            viewOrder = new ViewOrder();
        }
        setVisible(false);
        dispose();
        viewOrder.setVisible(true);
    }//GEN-LAST:event_viewOrderBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to log out", "Select", JOptionPane.YES_NO_CANCEL_OPTION);
        if (a == 0) {
            dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) catagoryTable.getModel();

        if (validateForm()) {
            String catagory = catagoryField.getText();
            rowIndex = catagoryTable.getSelectedRow();

            String idd = model.getValueAt(rowIndex, 0).toString();
            int id = Integer.parseInt(idd);
            try {
                query = "UPDATE CatagoryTable SET Catagory = ? WHERE Id = " + id;
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, catagory);
                ps.executeUpdate();

                updateItem(rowIndex, id);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        catagoryField.setText("");
        updateBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
        saveBtn.setEnabled(true);

    }//GEN-LAST:event_resetBtnActionPerformed

    private void catagoryTableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_catagoryTableComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_catagoryTableComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) catagoryTable.getModel();
        try {
            query = "SELECT * from CatagoryTable";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet set = ps.executeQuery();
            while (set.next()) {
                model.addRow(new Object[]{set.getInt("Id"), set.getString("Catagory")});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        updateBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private void catagoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catagoryTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) catagoryTable.getModel();
        rowIndex = catagoryTable.getSelectedRow();
        //getting value form the table
        int column = 1;
        String catagory = model.getValueAt(rowIndex, column).toString();
        //setting value in the catagory textfield
        catagoryField.setText(catagory);

        updateBtn.setEnabled(true);
        deleteBtn.setEnabled(true);
        saveBtn.setEnabled(false);

    }//GEN-LAST:event_catagoryTableMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            try {
                String catagory = catagoryField.getText();
                query = "INSERT into CatagoryTable(Catagory)VALUES(?)";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, catagory);
                ps.executeUpdate();

                addItemInTable(catagory);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Catagory field is empty");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) catagoryTable.getModel();
        rowIndex = catagoryTable.getSelectedRow();

        String idd = model.getValueAt(rowIndex, 0).toString();
        int id = Integer.parseInt(idd);

        if (rowIndex >= 0) {
            int i = JOptionPane.showConfirmDialog(null, "Do you want to delete Id " + id, "Select", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                try {
                    query = "DELETE FROM CatagoryTable WHERE Id = " + id;
                    PreparedStatement ps = con.prepareStatement(query);
                    ps.executeUpdate();

                    model.removeRow(rowIndex);
                    JOptionPane.showMessageDialog(null, "Id " + id + " deleted sucessfully");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
        catagoryField.setText("");
        saveBtn.setEnabled(true);
        deleteBtn.setEnabled(false);
        updateBtn.setEnabled(false);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void catagoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catagoryBtnActionPerformed
        // TODO add your handling code here:
        //NO code
    }//GEN-LAST:event_catagoryBtnActionPerformed

    //adding new item into the display table;
    private void addItemInTable(String catagory) {
    DefaultTableModel model = (DefaultTableModel) catagoryTable.getModel();
    try {
        query = "SELECT * from CatagoryTable WHERE Catagory = ?";
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, catagory);
        ResultSet set = ps.executeQuery();
        while (set.next()) {
            model.addRow(new Object[]{set.getString("Id"), set.getString("Catagory")});
            JOptionPane.showMessageDialog(null, catagory + " added sucessfully");
            catagoryField.setText("");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }

}

    private void updateItem(int rowIndex, int id) {
    DefaultTableModel model = (DefaultTableModel) catagoryTable.getModel();
    try {
        query = "SELECT * FROM CatagoryTable WHERE Id = ?";
        PreparedStatement ps = con.prepareStatement(query);
        ps.setInt(1, id);
        ResultSet set = ps.executeQuery();

        if (set.next()) {
            model.setValueAt(set.getInt("Id"), rowIndex, 0);
            model.setValueAt(set.getString("Catagory"), rowIndex, 1);
        }
        JOptionPane.showMessageDialog(null, id + " Updated sucessfully");
        catagoryField.setText("");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    updateBtn.setEnabled(false);
    deleteBtn.setEnabled(false);
    saveBtn.setEnabled(true);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Catagory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Catagory().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton catagoryBtn;
    private javax.swing.JTextField catagoryField;
    private javax.swing.JTable catagoryTable;
    private javax.swing.JButton customerBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton orderBtn;
    private javax.swing.JButton productBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton userBtn;
    private javax.swing.JButton viewOrderBtn;
    // End of variables declaration//GEN-END:variables

//Making connection with the database
    Connection con = Conn.getCon();

    String query;
    int rowIndex;
    String role = "superAdmin";
}
