package ims.project;

import database.Conn;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author abhi
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
    }

    public Customer(String role) {
        initComponents();
        if (role.equals("Admin")) {
            this.role = "Admin";
            userBtn.setVisible(false);
        }
    }

    private boolean validateForm() {
        if (nameField.getText().equals("") || phnoField.getText().equals("") || emailField.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userBtn = new javax.swing.JButton();
        catagoryBtn = new javax.swing.JButton();
        productBtn = new javax.swing.JButton();
        customerBtn = new javax.swing.JButton();
        orderBtn = new javax.swing.JButton();
        viewOrderBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phnoField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 1042, 533));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        userBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userBtn.setForeground(new java.awt.Color(255, 255, 255));
        userBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Users.png"))); // NOI18N
        userBtn.setText("User");
        userBtn.setBorder(null);
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });
        getContentPane().add(userBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, -1));

        catagoryBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        catagoryBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        catagoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        catagoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/category.png"))); // NOI18N
        catagoryBtn.setText("Catagory");
        catagoryBtn.setBorder(null);
        catagoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catagoryBtnActionPerformed(evt);
            }
        });
        getContentPane().add(catagoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 140, -1));

        productBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        productBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        productBtn.setForeground(new java.awt.Color(255, 255, 255));
        productBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/product.png"))); // NOI18N
        productBtn.setText("Product");
        productBtn.setBorder(null);
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });
        getContentPane().add(productBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 130, 40));

        customerBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        customerBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        customerBtn.setForeground(new java.awt.Color(255, 255, 255));
        customerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customers.png"))); // NOI18N
        customerBtn.setText("Customer");
        customerBtn.setToolTipText("");
        customerBtn.setBorder(null);
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 140, 40));

        orderBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        orderBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        orderBtn.setForeground(new java.awt.Color(255, 255, 255));
        orderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Orders.png"))); // NOI18N
        orderBtn.setText("Order");
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });
        getContentPane().add(orderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 40));

        viewOrderBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        viewOrderBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        viewOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewOrderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View-orders.png"))); // NOI18N
        viewOrderBtn.setText("View Order");
        viewOrderBtn.setBorder(null);
        viewOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 150, 40));

        logOutBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        logOutBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.setBorder(null);
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 140, -1));

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "PhNo", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 160, 670, 350));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CUSTOMER MANAGER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1040, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 60, -1));

        nameField.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 290, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone No");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 100, -1));

        phnoField.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        getContentPane().add(phnoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 290, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 60, -1));

        emailField.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 290, -1));

        updateBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 90, -1));

        saveBtn.setBackground(new java.awt.Color(102, 255, 51));
        saveBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, 90, -1));

        deleteBtn.setBackground(new java.awt.Color(255, 51, 51));
        deleteBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 90, -1));

        resetBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 90, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_background.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        // TODO add your handling code here:
        UserManager userManager;
        if (role.equals("Admin")) {
            userManager = new UserManager(role);
        } else {
            userManager = new UserManager();
        }
        setVisible(false);
        dispose();
        userManager.setVisible(true);
    }//GEN-LAST:event_userBtnActionPerformed

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        // TODO add your handling code here:
        Product product;
        if (role.equals("Admin")) {
            product = new Product(role);
        } else {
            product = new Product();
        }
        setVisible(false);
        dispose();
        product.setVisible(true);
    }//GEN-LAST:event_productBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:
        // NO code
    }//GEN-LAST:event_customerBtnActionPerformed

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        // TODO add your handling code here:
        Order order;
        if (role.equals("Admin")) {
            order = new Order(role);
        } else {
            order = new Order();
        }
        setVisible(false);
        dispose();
        order.setVisible(true);
    }//GEN-LAST:event_orderBtnActionPerformed

    private void viewOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderBtnActionPerformed
        // TODO add your handling code here:

        ViewOrder viewOrder;
        if (role.equals("Admin")) {
            viewOrder = new ViewOrder(role);
        } else {
            viewOrder = new ViewOrder();
        }
        setVisible(false);
        dispose();
        viewOrder.setVisible(true);
    }//GEN-LAST:event_viewOrderBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to log out", "Select", JOptionPane.YES_NO_CANCEL_OPTION);
        if (a == 0) {
            dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void catagoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catagoryBtnActionPerformed
        // TODO add your handling code here:

        Catagory catagory;
        if (role.equals("Admin")) {
            catagory = new Catagory(role);
        } else {
            catagory = new Catagory();
        }
        setVisible(false);
        dispose();
        catagory.setVisible(true);
    }//GEN-LAST:event_catagoryBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:

        if (validateForm()) {
            String name = nameField.getText();
            int phno = Integer.parseInt(phnoField.getText());
            String email = emailField.getText();

            try {
                query = "UPDATE customerTable SET name=?,mobile_number=?,email=?";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, name);
                ps.setInt(2, phno);
                ps.setString(3, email);
                ps.executeUpdate();

                resetFields();

                rowIndex = customerTable.getSelectedRow();
                updateItemInTable(rowIndex, phno, email);

                updateBtn.setEnabled(false);
                deleteBtn.setEnabled(false);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Fill all fields");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:

        if (validateForm()) {
            String name = nameField.getText();
            int phno = Integer.parseInt(phnoField.getText());
            String email = emailField.getText();

            try {
                query = "INSERT INTO customerTable (name,mobile_number,email) VALUES(?,?,?)";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, name);
                ps.setInt(2, phno);
                ps.setString(3, email);
                ps.executeUpdate();

                resetFields();

                addItemInTable(phno, email);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Fill all fields");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) customerTable.getModel();

        String idd = model.getValueAt(rowIndex, 0).toString();
        int id = Integer.parseInt(idd);

        if (JOptionPane.showConfirmDialog(null, "Do you wnat to delete id " + id, "Selected", JOptionPane.YES_NO_OPTION) == 0) {
            try {
                query = "DELETE FROM customerTable WHERE id = ?";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setInt(1, id);
                ps.executeUpdate();

                model.removeRow(rowIndex);

                updateBtn.setEnabled(false);
                deleteBtn.setEnabled(false);
                resetFields();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        resetFields();
        updateBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
        saveBtn.setEnabled(true);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) customerTable.getModel();

        try {
            query = "SELECT * FROM customerTable";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet set = ps.executeQuery();
            while (set.next()) {
                model.addRow(new Object[]{set.getInt("id"), set.getString("name"), set.getInt("mobile_number"), set.getString("email")});

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        updateBtn.setEnabled(false);
        deleteBtn.setEnabled(false);

    }//GEN-LAST:event_formComponentShown

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) customerTable.getModel();
        rowIndex = customerTable.getSelectedRow();

        String name = model.getValueAt(rowIndex, 1).toString();
        String phno = model.getValueAt(rowIndex, 2).toString();
        String email = model.getValueAt(rowIndex, 3).toString();

        nameField.setText(name);
        phnoField.setText(phno);
        emailField.setText(email);

        updateBtn.setEnabled(true);
        deleteBtn.setEnabled(true);
        saveBtn.setEnabled(false);
    }//GEN-LAST:event_customerTableMouseClicked

    private void addItemInTable(int phno, String email) {
        DefaultTableModel model = (DefaultTableModel) customerTable.getModel();

        try {
            query = "SELECT * FROM customerTable WHERE mobile_number = ? and email = ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setInt(1, phno);
            ps.setString(2, email);
            ResultSet set = ps.executeQuery();
            if (set.next()) {
                model.addRow(new Object[]{set.getInt("id"), set.getString("name"), set.getInt("mobile_number"), set.getString("email")});
                JOptionPane.showMessageDialog(null, set.getString("name") + " added sucessfully");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void updateItemInTable(int rowIndex, int phno, String email) {
        DefaultTableModel model = (DefaultTableModel) customerTable.getModel();

        try {
            query = "SELECT * FROM customerTable WHERE mobile_number = ? and email = ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setInt(1, phno);
            ps.setString(2, email);
            ResultSet set = ps.executeQuery();
            if (set.next()) {
                model.setValueAt(set.getInt("id"), rowIndex, 0);
                model.setValueAt(set.getString("name"), rowIndex, 1);
                model.setValueAt(set.getInt("mobile_number"), rowIndex, 2);
                model.setValueAt(set.getString("email"), rowIndex, 3);
            }
            JOptionPane.showMessageDialog(null, set.getString("name") + " Updated sucessfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void resetFields() {
        nameField.setText("");
        phnoField.setText("");
        emailField.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton catagoryBtn;
    private javax.swing.JButton customerBtn;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton orderBtn;
    private javax.swing.JTextField phnoField;
    private javax.swing.JButton productBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton userBtn;
    private javax.swing.JButton viewOrderBtn;
    // End of variables declaration//GEN-END:variables

    Connection con = Conn.getCon();
    String query;
    int rowIndex;
    String role = "superAdmin";
}
