/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ims.project;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import common.OpenPdf;
import database.InventoryUtils;
import ims.project.*;
import ims.project.Product;
import javax.swing.*;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abhi
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
    }

    public Order(String role) {
        initComponents();
        if (role.equals("Admin")) {
            this.role = "Admin";
            userBtn.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logOutBtn = new javax.swing.JButton();
        viewOrderBtn = new javax.swing.JButton();
        orderBtn = new javax.swing.JButton();
        customerBtn = new javax.swing.JButton();
        productBtn = new javax.swing.JButton();
        catagoryBtn = new javax.swing.JButton();
        userBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        addToCartBtn = new javax.swing.JButton();
        orderQuantity = new javax.swing.JSpinner();
        totalAmtLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 1042, 533));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logOutBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        logOutBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.setBorder(null);
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 140, -1));

        viewOrderBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        viewOrderBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        viewOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewOrderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View-orders.png"))); // NOI18N
        viewOrderBtn.setText("View Order");
        viewOrderBtn.setBorder(null);
        viewOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 150, 40));

        orderBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        orderBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        orderBtn.setForeground(new java.awt.Color(255, 255, 255));
        orderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Orders.png"))); // NOI18N
        orderBtn.setText("Order");
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });
        getContentPane().add(orderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 40));

        customerBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        customerBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        customerBtn.setForeground(new java.awt.Color(255, 255, 255));
        customerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customers.png"))); // NOI18N
        customerBtn.setText("Customer");
        customerBtn.setToolTipText("");
        customerBtn.setBorder(null);
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 140, 40));

        productBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        productBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        productBtn.setForeground(new java.awt.Color(255, 255, 255));
        productBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/product.png"))); // NOI18N
        productBtn.setText("Product");
        productBtn.setBorder(null);
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });
        getContentPane().add(productBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 130, 40));

        catagoryBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        catagoryBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        catagoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        catagoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/category.png"))); // NOI18N
        catagoryBtn.setText("Catagory");
        catagoryBtn.setBorder(null);
        catagoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catagoryBtnActionPerformed(evt);
            }
        });
        getContentPane().add(catagoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 140, -1));

        userBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        userBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userBtn.setForeground(new java.awt.Color(255, 255, 255));
        userBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Users.png"))); // NOI18N
        userBtn.setText("User");
        userBtn.setBorder(null);
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });
        getContentPane().add(userBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ORDER MANAGER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 420, -1));

        productTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Quantity", "Price", "Description", "Catagory Id", "Catagory"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(productTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 570, 190));

        cartTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Name", "Quantity", "Price", "Discripton", "Sub Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(cartTable);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 440, 150));

        customerTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "PhNo", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 340, 150));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CART");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product List");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer List");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Order Quantity ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Amount : Rs");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, -1, 30));

        deleteBtn.setBackground(new java.awt.Color(255, 0, 51));
        deleteBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 100, -1));

        saveBtn.setBackground(new java.awt.Color(51, 255, 0));
        saveBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save Order Details");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 190, -1));

        addToCartBtn.setBackground(new java.awt.Color(0, 204, 204));
        addToCartBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        addToCartBtn.setForeground(new java.awt.Color(255, 255, 255));
        addToCartBtn.setText("Add To Cart");
        addToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addToCartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 367, 130, 40));

        orderQuantity.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        orderQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        orderQuantity.setName(""); // NOI18N
        orderQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                orderQuantityStateChanged(evt);
            }
        });
        getContentPane().add(orderQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 100, -1));

        totalAmtLbl.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        totalAmtLbl.setForeground(new java.awt.Color(255, 255, 255));
        totalAmtLbl.setText("00.00");
        getContentPane().add(totalAmtLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_background.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to log out", "Select", JOptionPane.YES_NO_CANCEL_OPTION);
        if (a == 0) {
            dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void viewOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderBtnActionPerformed
        // TODO add your handling code here:

        ViewOrder viewOrder;
        if (role.equals("Admin")) {
            viewOrder = new ViewOrder(role);
        } else {
            viewOrder = new ViewOrder();
        }
        setVisible(false);
        dispose();
        viewOrder.setVisible(true);
    }//GEN-LAST:event_viewOrderBtnActionPerformed

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        // TODO add your handling code here:
        //No code
    }//GEN-LAST:event_orderBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:
        Customer customer;
        if (role.equals("Admin")) {
            customer = new Customer(role);
        } else {
            customer = new Customer();
        }
        setVisible(false);
        dispose();
        customer.setVisible(true);
    }//GEN-LAST:event_customerBtnActionPerformed

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        // TODO add your handling code here:
        Product product;
        if (role.equals("Admin")) {
            product = new Product(role);
        } else {
            product = new Product();
        }
        setVisible(false);
        dispose();
        product.setVisible(true);
    }//GEN-LAST:event_productBtnActionPerformed

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        // TODO add your handling code here:
        UserManager userManager;
        if (role.equals("Admin")) {
            userManager = new UserManager(role);
        } else {
            userManager = new UserManager();
        }
        setVisible(false);
        dispose();
        userManager.setVisible(true);
    }//GEN-LAST:event_userBtnActionPerformed

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        int rowIndex = productTable.getSelectedRow();

        //product table data
        productId = Integer.parseInt(model.getValueAt(rowIndex, 0).toString());
        productName = model.getValueAt(rowIndex, 1).toString();
        productQuantity = Integer.parseInt(model.getValueAt(rowIndex, 2).toString());
        productPrice = Float.parseFloat(model.getValueAt(rowIndex, 3).toString());
        productDesc = model.getValueAt(rowIndex, 4).toString();

        orderQuantity.setEnabled(true);
    }//GEN-LAST:event_productTableMouseClicked

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
        //making orderId
        String orderId = getUniqueId("Bill-");

        if (totalAmt < 1) {
            JOptionPane.showMessageDialog(null, "Cart is empty");
        } else {
            try {
                // Updating the product table quantity
                if (cartTable.getRowCount() != 0) {
                    for (int i = 0; i < cartTable.getRowCount(); i++) {
                        try {
                            DefaultTableModel mod = (DefaultTableModel) cartTable.getModel();

                            // Extracting product ID and quantity from the cartTable
                            String productId = mod.getValueAt(i, 0).toString();
                            String quantityStr = mod.getValueAt(i, 2).toString();

                            // Validating if the quantity value is a valid integer
                            int quantity = 0;
                            try {
                                quantity = Integer.parseInt(quantityStr);
                            } catch (NumberFormatException e) {
                                JOptionPane.showMessageDialog(null, "Invalid quantity value: " + quantityStr);
                                continue; // Skip this iteration
                            }

                            // Prepare the update query for the ProductTable
                            String query = "UPDATE ProductTable SET Quantity = Quantity - ? WHERE Id = ?";
                            PreparedStatement ps = con.prepareStatement(query);
                            ps.setInt(1, quantity);
                            ps.setInt(2, Integer.parseInt(productId));
                            ps.executeUpdate();
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
                        }
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
            try {
                SimpleDateFormat myFormat = new SimpleDateFormat("dd-mm-yyyy");
                Calendar cal = Calendar.getInstance();
                query = "INSERT into orderDetails(orderId,customer_id,orderDate,totalPaid) VALUES(?,?,?,?)";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, orderId);
                ps.setInt(2, customerId);
                ps.setString(3, myFormat.format(cal.getTime()));
                ps.setFloat(4, totalAmt);
                ps.executeUpdate();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            JOptionPane.showMessageDialog(null, "Order saved");

            //creating pdf
            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            try {
                SimpleDateFormat myFormat = new SimpleDateFormat("dd-mm-yyyy");
                Calendar cal = Calendar.getInstance();

                PdfWriter.getInstance(doc, new FileOutputStream(InventoryUtils.billPath + "" + orderId + ".pdf"));
                doc.open();
                Paragraph starline = new Paragraph("**************************************************");
                Paragraph projectName = new Paragraph("                    IMS Project                   ");
                Paragraph details = new Paragraph("\tOrder Id : " + orderId + "\nDate: " + myFormat.format(cal.getTime()) + "\nTotal Paid: " + totalAmt);

                doc.add(starline);
                doc.add(projectName);
                doc.add(starline);
                doc.add(details);
                doc.add(starline);

                PdfPTable tb1 = new PdfPTable(5);
                PdfPCell nameCell = new PdfPCell(new Phrase("Name"));
                PdfPCell descCell = new PdfPCell(new Phrase("Description"));
                PdfPCell priceCell = new PdfPCell(new Phrase("Price"));
                PdfPCell quantityCell = new PdfPCell(new Phrase("Quantity"));
                PdfPCell subTotalPriceCell = new PdfPCell(new Phrase("SubTotal Price"));

                BaseColor backgroundColor = new BaseColor(255, 204, 51);
                nameCell.setBackgroundColor(backgroundColor);
                descCell.setBackgroundColor(backgroundColor);
                priceCell.setBackgroundColor(backgroundColor);
                quantityCell.setBackgroundColor(backgroundColor);
                subTotalPriceCell.setBackgroundColor(backgroundColor);

                tb1.addCell(nameCell);
                tb1.addCell(descCell);
                tb1.addCell(priceCell);
                tb1.addCell(quantityCell);
                tb1.addCell(subTotalPriceCell);

                for (int i = 0; i < cartTable.getRowCount(); i++) {
                    tb1.addCell(cartTable.getValueAt(i, 1).toString());
                    tb1.addCell(cartTable.getValueAt(i, 4).toString());
                    tb1.addCell(cartTable.getValueAt(i, 3).toString());
                    tb1.addCell(cartTable.getValueAt(i, 2).toString());
                    tb1.addCell(cartTable.getValueAt(i, 5).toString());
                }

                doc.add(tb1);
                doc.add(starline);
                Paragraph thanksMsg = new Paragraph("Thank you !, Please Visit Again");
                doc.add(thanksMsg);

                //opening the pdf
                OpenPdf.openById(orderId);

                setVisible(false);
                dispose();
                new Order().setVisible(true);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            doc.close();
//            setVisible(false);
//            new Order().setVisible(true);
        }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
        int i = JOptionPane.showConfirmDialog(null, "Do you want to remove " + productName + " from cart.", "Selected", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            int rowIndex = cartTable.getSelectedRow();
            //updating the total amount label
            float temp = Float.parseFloat(model.getValueAt(rowIndex, 5).toString());
            totalAmt -= temp;
            totalAmtLbl.setText(String.valueOf(totalAmt));
            model.removeRow(rowIndex);
        }
        deleteBtn.setEnabled(false);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void addToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();

        int rowIndexProductTable = productTable.getSelectedRow();
        int rowIndexCustomerTable = customerTable.getSelectedRow();
        boolean flag = true;

        if (rowIndexProductTable >= 0 && rowIndexCustomerTable >= 0) {
            //checking whether a product already exit in the cart or not
            int rowIndex = 0;
            for (rowIndex = 0; rowIndex < cartTable.getRowCount(); rowIndex++) {
                int id = Integer.parseInt(model.getValueAt(rowIndex, 0).toString());
                if (productId == id) {
                    flag = false;
                    break;
                }
            }
            int left = productQuantity - selectedQuantity;
            if (productQuantity == 0) {
                JOptionPane.showMessageDialog(null, "Product is out of stock");
            } else if (productQuantity - selectedQuantity < 0) {
                JOptionPane.showMessageDialog(null, "Only " + productQuantity + " Product left in stock");
            } else {
                //adding product in the cart if flag is true( if product is not already in cart)
                if (flag) {
                    //calculating subtotal
                    subTotal = productPrice * selectedQuantity;
                    //adding product in the cart
                    try {
                        model.addRow(new Object[]{productId, productName, selectedQuantity, productPrice, productDesc, subTotal});
                        JOptionPane.showMessageDialog(null, productName + " added to cart");
                        productTable.clearSelection();
                        orderQuantity.setValue(1);
                        orderQuantity.setEnabled(false);

                        //setting the total amount label
                        totalAmt += subTotal;
                        totalAmtLbl.setText(String.valueOf(totalAmt));

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } else {
                    int choice = JOptionPane.showConfirmDialog(null, productName + " already in cart.\n Want to update the quanity ?", "Selected", JOptionPane.YES_NO_OPTION);
                    if (choice == 0) {
                        float subTotal = productPrice * selectedQuantity;
                        //updating the total amount label
                        float temp = Float.parseFloat(model.getValueAt(rowIndex, 5).toString());
                        totalAmt -= temp;
                        totalAmt += subTotal;
                        totalAmtLbl.setText(String.valueOf(totalAmt));

                        //updating cart
                        model.setValueAt(selectedQuantity, rowIndex, 2);
                        model.setValueAt(subTotal, rowIndex, 5);
                        productTable.clearSelection();
                        orderQuantity.setValue(1);
                        orderQuantity.setEnabled(false);
                    }
                }
            }

        } else {
            if (rowIndexProductTable < 0) {
                JOptionPane.showMessageDialog(null, "No Product is selected");
            } else {
                JOptionPane.showMessageDialog(null, "No Customer is selected");
            }
        }
    }//GEN-LAST:event_addToCartBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel) productTable.getModel();

        try {
            query = "SELECT * FROM ProductTable INNER JOIN CatagoryTable ON ProductTable.catagory_id = CatagoryTable.id";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet set = ps.executeQuery();
            while (set.next()) {
                model1.addRow(new Object[]{set.getInt("id"), set.getString("name"), set.getInt("Quantity"), set.getFloat("Price"), set.getString("Description"), set.getInt("catagory_id"), set.getString(8)});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        DefaultTableModel model2 = (DefaultTableModel) customerTable.getModel();
        // showing customer table
        try {
            query = "SELECT * FROM customerTable";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet set = ps.executeQuery();
            while (set.next()) {
                model2.addRow(new Object[]{set.getInt("id"), set.getString("name"), set.getInt("mobile_number"), set.getString("email")});

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        deleteBtn.setEnabled(false);
        orderQuantity.setEnabled(false);

    }//GEN-LAST:event_formComponentShown

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) customerTable.getModel();

        int rowIndex = customerTable.getSelectedRow();

        customerId = Integer.parseInt(model.getValueAt(rowIndex, 0).toString());
        customerName = model.getValueAt(rowIndex, 1).toString();
        customerPhno = Integer.parseInt(model.getValueAt(rowIndex, 2).toString());
        customerEmail = model.getValueAt(rowIndex, 3).toString();
    }//GEN-LAST:event_customerTableMouseClicked

    private void orderQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_orderQuantityStateChanged
        selectedQuantity = Integer.parseInt(orderQuantity.getValue().toString());

    }//GEN-LAST:event_orderQuantityStateChanged

    private void cartTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
        int rowIndex = cartTable.getSelectedRow();

        cartProductId = Integer.parseInt(model.getValueAt(rowIndex, 0).toString());
        cartProductName = model.getValueAt(rowIndex, 1).toString();
        cartProductQuantity = Integer.parseInt(model.getValueAt(rowIndex, 2).toString());;
        cartProductPrice = Float.parseFloat(model.getValueAt(rowIndex, 3).toString());
        cartProductDesc = model.getValueAt(rowIndex, 4).toString();
        subTotal = Float.parseFloat(model.getValueAt(rowIndex, 5).toString());

        deleteBtn.setEnabled(true);
    }//GEN-LAST:event_cartTableMouseClicked

    private void catagoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catagoryBtnActionPerformed
        // TODO add your handling code here:

        Catagory catagory;
        if (role.equals("Admin")) {
            catagory = new Catagory(role);
        } else {
            catagory = new Catagory();
        }
        setVisible(false);
        dispose();
        catagory.setVisible(true);
    }//GEN-LAST:event_catagoryBtnActionPerformed

    private String getUniqueId(String perfix) {
        return perfix + System.nanoTime();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartBtn;
    private javax.swing.JTable cartTable;
    private javax.swing.JButton catagoryBtn;
    private javax.swing.JButton customerBtn;
    private javax.swing.JTable customerTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton orderBtn;
    private javax.swing.JSpinner orderQuantity;
    private javax.swing.JButton productBtn;
    private javax.swing.JTable productTable;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel totalAmtLbl;
    private javax.swing.JButton userBtn;
    private javax.swing.JButton viewOrderBtn;
    // End of variables declaration//GEN-END:variables

    Connection con = database.Conn.getCon();
    String query;

    //productTable variable
    int productId;
    String productName;
    int productQuantity;
    float productPrice;
    String productDesc;
    int selectedQuantity = 1;

    //customerTable variables;
    int customerId;
    String customerName;
    int customerPhno;
    String customerEmail;

    //cartTable variables
    int cartProductId;
    String cartProductName;
    int cartProductQuantity;
    float cartProductPrice;
    String cartProductDesc;
    float subTotal;
    float totalAmt;

    String role = "superAdmin";
}
