/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ims.project;

import javax.swing.*;
import java.sql.*;

import database.Conn;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abhi
 */
public class Product extends javax.swing.JFrame {

    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
    }

    public Product(String role) {
        initComponents();
        if (role.equals("Admin")) {
            this.role = "Admin";
            userBtn.setVisible(false);
        }
    }

    private boolean validateForm() {
        if (nameField.getText().equals("") || quantityField.getText().equals("") || priceField.getText().equals("") || descriptionField.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    private void getCatagoryItems() {
        catagoryBox.removeAllItems();
        try {
            query = "SELECT * FROM CatagoryTable";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet set = ps.executeQuery();

            while (set.next()) {
                String item = set.getInt("id") + "-" + set.getString("catagory");
                catagoryBox.addItem(item);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userBtn = new javax.swing.JButton();
        catagoryBtn = new javax.swing.JButton();
        productBtn = new javax.swing.JButton();
        customerBtn = new javax.swing.JButton();
        orderBtn = new javax.swing.JButton();
        viewOrderBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        descriptionField = new javax.swing.JTextArea();
        resetBtn = new javax.swing.JButton();
        catagoryBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 1042, 533));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        userBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userBtn.setForeground(new java.awt.Color(255, 255, 255));
        userBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Users.png"))); // NOI18N
        userBtn.setText("User");
        userBtn.setBorder(null);
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });
        getContentPane().add(userBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, -1));

        catagoryBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        catagoryBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        catagoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        catagoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/category.png"))); // NOI18N
        catagoryBtn.setText("Catagory");
        catagoryBtn.setBorder(null);
        catagoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catagoryBtnActionPerformed(evt);
            }
        });
        getContentPane().add(catagoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 140, -1));

        productBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        productBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        productBtn.setForeground(new java.awt.Color(255, 255, 255));
        productBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/product.png"))); // NOI18N
        productBtn.setText("Product");
        productBtn.setBorder(null);
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });
        getContentPane().add(productBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 130, 40));

        customerBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        customerBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        customerBtn.setForeground(new java.awt.Color(255, 255, 255));
        customerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customers.png"))); // NOI18N
        customerBtn.setText("Customer");
        customerBtn.setToolTipText("");
        customerBtn.setBorder(null);
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 140, 40));

        orderBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        orderBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        orderBtn.setForeground(new java.awt.Color(255, 255, 255));
        orderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Orders.png"))); // NOI18N
        orderBtn.setText("Order");
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });
        getContentPane().add(orderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 40));

        viewOrderBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        viewOrderBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        viewOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewOrderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View-orders.png"))); // NOI18N
        viewOrderBtn.setText("View Order");
        viewOrderBtn.setBorder(null);
        viewOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 150, 40));

        logOutBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        logOutBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.setBorder(null);
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 140, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE PRODUCT");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1040, -1));

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Quantity", "Price", "Description", "Catagory Id", "Catagory"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);
        if (productTable.getColumnModel().getColumnCount() > 0) {
            productTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 690, 370));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, -1, 20));

        nameField.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 190, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantity");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, -1, -1));

        quantityField.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        quantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityFieldActionPerformed(evt);
            }
        });
        getContentPane().add(quantityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, 190, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, -1, -1));

        priceField.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });
        getContentPane().add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 190, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Catagory");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, -1, -1));

        descriptionField.setColumns(20);
        descriptionField.setLineWrap(true);
        descriptionField.setRows(5);
        descriptionField.setWrapStyleWord(true);
        getContentPane().add(descriptionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 260, 60));

        resetBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 90, -1));

        catagoryBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        catagoryBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catagoryBoxActionPerformed(evt);
            }
        });
        getContentPane().add(catagoryBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 360, 180, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Description");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, -1, -1));

        saveBtn.setBackground(new java.awt.Color(102, 255, 51));
        saveBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, 90, -1));

        deleteBtn.setBackground(new java.awt.Color(255, 51, 51));
        deleteBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 90, -1));

        updateBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 90, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_background.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        // TODO add your handling code here:
        UserManager userManager;
        if (role.equals("Admin")) {
            userManager = new UserManager(role);
        } else {
            userManager = new UserManager();
        }
        setVisible(false);
        dispose();
        userManager.setVisible(true);

    }//GEN-LAST:event_userBtnActionPerformed

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        // TODO add your handling code here:
// NO Code
    }//GEN-LAST:event_productBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:
        Customer customer;
        if (role.equals("Admin")) {
            customer = new Customer(role);
        } else {
            customer = new Customer();
        }
        setVisible(false);
        dispose();
        customer.setVisible(true);
    }//GEN-LAST:event_customerBtnActionPerformed

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        // TODO add your handling code here:
        Order order;
        if (role.equals("Admin")) {
            order = new Order(role);
        } else {
            order = new Order();
        }
        setVisible(false);
        dispose();
        order.setVisible(true);
    }//GEN-LAST:event_orderBtnActionPerformed

    private void viewOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderBtnActionPerformed
        // TODO add your handling code here:

        ViewOrder viewOrder;
        if (role.equals("Admin")) {
            viewOrder = new ViewOrder(role);
        } else {
            viewOrder = new ViewOrder();
        }
        setVisible(false);
        dispose();
        viewOrder.setVisible(true);
    }//GEN-LAST:event_viewOrderBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to log out", "Select", JOptionPane.YES_NO_CANCEL_OPTION);
        if (a == 0) {
            Login login = new Login();
            setVisible(false);
            dispose();
            login.setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void catagoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catagoryBtnActionPerformed
        // TODO add your handling code here:

        Catagory catagory;
        if (role.equals("Admin")) {
            catagory = new Catagory(role);
        } else {
            catagory = new Catagory();
        }
        setVisible(false);
        dispose();
        catagory.setVisible(true);
    }//GEN-LAST:event_catagoryBtnActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void quantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityFieldActionPerformed

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void catagoryBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catagoryBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catagoryBoxActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:jButton3
        getCatagoryItems();
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        try {
            query = "SELECT * FROM ProductTable INNER JOIN CatagoryTable ON ProductTable.catagory_id = CatagoryTable.Id";
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet set = ps.executeQuery();
            while (set.next()) {
                model.addRow(new Object[]{set.getInt("id"), set.getString("name"), set.getInt("Quantity"), set.getFloat("Price"), set.getString("Description"), set.getInt("catagory_id"), set.getString(8)});
                System.out.println(1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        updateBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:

        if (validateForm()) {
            String name = nameField.getText();
            int quantity = Integer.parseInt(quantityField.getText());
            float price = Float.parseFloat(priceField.getText());
            String description = descriptionField.getText();
            String catagory = catagoryBox.getSelectedItem().toString();
            String catagoryId[] = catagory.split("-", 0);// 0 limit on index;

            try {
                query = "INSERT INTO ProductTable (name,quantity,price,description,catagory_id) VALUES(?,?,?,?,?)";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, name);
                ps.setInt(2, quantity);
                ps.setFloat(3, price);
                ps.setString(4, description);
                ps.setString(5, catagoryId[0]);
                ps.executeUpdate();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }

            resetFields();

            addItemInTable(catagoryId[0], name);
            
            JOptionPane.showMessageDialog(null, name+" added successfully");
            saveBtn.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Fill all fields");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        rowIndex = productTable.getSelectedRow();

        nameField.setText(model.getValueAt(rowIndex, 1).toString());
        quantityField.setText(model.getValueAt(rowIndex, 2).toString());
        priceField.setText(model.getValueAt(rowIndex, 3).toString());
        descriptionField.setText(model.getValueAt(rowIndex, 4).toString());

        int catagoryId = Integer.parseInt(model.getValueAt(rowIndex, 5).toString());
        String catagoryName = model.getValueAt(rowIndex, 6).toString();
        catagoryBox.setSelectedItem(catagoryId + "-" + catagoryName);
//        if(catagoryBox.getSelectedItem().toString().equals())

        updateBtn.setEnabled(true);
        deleteBtn.setEnabled(true);
        saveBtn.setEnabled(false);
    }//GEN-LAST:event_productTableMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        rowIndex = productTable.getSelectedRow();

        String name = nameField.getText();
        int quantity = Integer.parseInt(quantityField.getText());
        float price = Float.parseFloat((priceField.getText().trim()));
        String description = descriptionField.getText();
        String catagory = catagoryBox.getSelectedItem().toString();
        String catagoryIdd[] = catagory.split("-", 0);
        int catagoryId = Integer.parseInt(catagoryIdd[0]);

        String idd = model.getValueAt(rowIndex, 0).toString();
        int id = Integer.parseInt(idd);

        if (validateForm()) {
            // Show confirmation dialog
            if (JOptionPane.showConfirmDialog(null, "Do you want to update?", "Selected", JOptionPane.YES_NO_OPTION) == 0) {
                try {
                    // Corrected SQL query
                    String query = "UPDATE ProductTable SET name=?, quantity=?, price=?, description=?, catagory_id=? WHERE Id=?";

                    // Prepare the statement
                    PreparedStatement ps = con.prepareStatement(query);
                    ps.setString(1, name);          // Replace 'name' with actual variable holding the name
                    ps.setInt(2, quantity);         // Replace 'quantity' with actual variable
                    ps.setFloat(3, price);          // Replace 'price' with actual variable
                    ps.setString(4, description);   // Replace 'description' with actual variable
                    ps.setInt(5, catagoryId);       // Replace 'catagoryId' with actual variable
                    ps.setInt(6, id);               // Replace 'id' with actual variable

                    // Execute the update
                    int rowsAffected = ps.executeUpdate();

                    if (rowsAffected > 0) {
                        // Update successful
                        updateItem(rowIndex, id); // Update the UI or data structure
                        JOptionPane.showMessageDialog(null, "Updated successfully!");
                        resetFields();           // Reset fields in your form
                    } else {
                        // No rows affected
                        JOptionPane.showMessageDialog(null, "No record found to update!");
                    }
                } catch (SQLException e) {
                    // Handle SQL exceptions
                    JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
                }
            }
        } else {
            // Validation failed
            JOptionPane.showMessageDialog(null, "Fill all details");
        }


    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();

        String idd = model.getValueAt(rowIndex, 0).toString();
        int id = Integer.parseInt(idd);

        if (JOptionPane.showConfirmDialog(null, "Do you wnat to delete id " + id, "Selected", JOptionPane.YES_NO_OPTION) == 0) {
            try {
                query = "DELETE FROM ProductTable WHERE id = ?";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setInt(1, id);
                ps.executeUpdate();

                model.removeRow(rowIndex);

                resetFields();
                saveBtn.setEnabled(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }

    }//GEN-LAST:event_deleteBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        resetFields();
        updateBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
        saveBtn.setEnabled(true);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void addItemInTable(String catagoryId, String name) {
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        try {
            query = "SELECT * FROM ProductTable INNER JOIN CatagoryTable ON ProductTable.catagory_id = CatagoryTable.id WHERE catagory_id = ? AND name = ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, catagoryId);
            ps.setString(2, name);
            ResultSet set = ps.executeQuery();
            if (set.next()) {
                model.addRow(new Object[]{set.getString("id"), set.getString("name"), set.getInt("quantity"), set.getFloat("price"), set.getString("description"), set.getInt("catagory_id"), set.getString(8)});
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void updateItem(int rowIndex, int id) {
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();

        try {
            query = "SELECT * FROM ProductTable where id = ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setInt(1, id);
            ResultSet set = ps.executeQuery();
            if (set.next()) {
                model.setValueAt(set.getInt("id"), rowIndex, 0);
                model.setValueAt(set.getString("name"), rowIndex, 1);
                model.setValueAt(set.getInt("quantity"), rowIndex, 2);
                model.setValueAt(set.getFloat("price"), rowIndex, 3);
                model.setValueAt(set.getString("description"), rowIndex, 4);
                model.setValueAt(set.getInt("id"), rowIndex, 5);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void resetFields() {
        nameField.setText("");
        quantityField.setText("");
        priceField.setText("");
        descriptionField.setText("");
        catagoryBox.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> catagoryBox;
    private javax.swing.JButton catagoryBtn;
    private javax.swing.JButton customerBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextArea descriptionField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton orderBtn;
    private javax.swing.JTextField priceField;
    private javax.swing.JButton productBtn;
    private javax.swing.JTable productTable;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton userBtn;
    private javax.swing.JButton viewOrderBtn;
    // End of variables declaration//GEN-END:variables

    //getting connection
    Connection con = Conn.getCon();
    String query;
    int rowIndex;
    String role = "superAdmin";

}
