/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ims.project;

import javax.swing.*;
import java.awt.*;
import java.sql.*;
import javax.swing.table.*;

import database.Conn;

/**
 *
 * @author abhi
 */
public class UserManager extends javax.swing.JFrame {
    /**
     * Creates new form HomePage
     */
    public UserManager() {
        initComponents();
    }

    public UserManager(String role) {
//        setLocationRelativeTo(null);
        initComponents();
        if (role.equals("Admin")) {
            userBtn.setVisible(false);
            dispose();
            new Customer().setVisible(true);
        }
        updateBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
    }

    //validate the input fields are empty or filled
    private boolean validateForm() {
        char[] ch = passwordfield.getPassword();
        String password = new String(ch);

        if (namefield.getText().equals("") || phonefield.getText().equals("") || emailfield.getText().equals("") || addressfield.getText().equals("") || password.equals("")) {
            return false;
        } else {
            return true;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerBtn = new javax.swing.JButton();
        productBtn = new javax.swing.JButton();
        userBtn = new javax.swing.JButton();
        catagoryBtn = new javax.swing.JButton();
        viewOrderBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        orderBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        statusbox = new javax.swing.JComboBox<>();
        addressfield = new javax.swing.JTextArea();
        emailfield = new javax.swing.JTextField();
        phonefield = new javax.swing.JTextField();
        passwordfield = new javax.swing.JPasswordField();
        namefield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(100, 100, 1042, 533));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        setLocation(new java.awt.Point(100, 100));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        customerBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        customerBtn.setForeground(new java.awt.Color(255, 255, 255));
        customerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customers.png"))); // NOI18N
        customerBtn.setText("Customer");
        customerBtn.setToolTipText("");
        customerBtn.setBorder(null);
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 140, 40));

        productBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        productBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        productBtn.setForeground(new java.awt.Color(255, 255, 255));
        productBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/product.png"))); // NOI18N
        productBtn.setText("Product");
        productBtn.setBorder(null);
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });
        getContentPane().add(productBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 130, 40));

        userBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        userBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userBtn.setForeground(new java.awt.Color(255, 255, 255));
        userBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Users.png"))); // NOI18N
        userBtn.setText("User");
        userBtn.setBorder(null);
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });
        getContentPane().add(userBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, -1));

        catagoryBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        catagoryBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        catagoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        catagoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/category.png"))); // NOI18N
        catagoryBtn.setText("Catagory");
        catagoryBtn.setBorder(null);
        catagoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catagoryBtnActionPerformed(evt);
            }
        });
        getContentPane().add(catagoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 140, -1));

        viewOrderBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        viewOrderBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        viewOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewOrderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/View-orders.png"))); // NOI18N
        viewOrderBtn.setText("View Order");
        viewOrderBtn.setBorder(null);
        viewOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 150, 40));

        logOutBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        logOutBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.setBorder(null);
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 140, -1));

        orderBtn.setBackground(java.awt.SystemColor.activeCaptionBorder);
        orderBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        orderBtn.setForeground(new java.awt.Color(255, 255, 255));
        orderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Orders.png"))); // NOI18N
        orderBtn.setText("Order");
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });
        getContentPane().add(orderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 40));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "PhNo", "Email", "Adress", "Status", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);
        if (userTable.getColumnModel().getColumnCount() > 0) {
            userTable.getColumnModel().getColumn(0).setPreferredWidth(5);
            userTable.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 610, 370));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USER  MANAGER  PORTAL");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1040, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobile Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Adress");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, -1, -1));

        saveBtn.setBackground(new java.awt.Color(102, 255, 102));
        saveBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 440, 110, -1));

        updateBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 110, -1));

        resetBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 480, 110, -1));

        deleteBtn.setBackground(new java.awt.Color(255, 51, 51));
        deleteBtn.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete ");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 110, -1));

        statusbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "InActive" }));
        getContentPane().add(statusbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, -1, -1));

        addressfield.setColumns(20);
        addressfield.setRows(5);
        addressfield.setWrapStyleWord(true);
        getContentPane().add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 230, 80));

        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 230, -1));

        phonefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonefieldActionPerformed(evt);
            }
        });
        getContentPane().add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 230, -1));
        getContentPane().add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 230, -1));

        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        getContentPane().add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 230, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
//        UserManager homePage = new UserManager();
//        setVisible(false);
//        dispose();
//        homePage.setVisible(true);
    }//GEN-LAST:event_userBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:
        Customer customer = new Customer();
        setVisible(false);
        dispose();
        customer.setVisible(true);
    }//GEN-LAST:event_customerBtnActionPerformed

    private void viewOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderBtnActionPerformed
        // TODO add your handling code here:
        ViewOrder viewOrder = new ViewOrder();
        setVisible(false);
        dispose();
        viewOrder.setVisible(true);
    }//GEN-LAST:event_viewOrderBtnActionPerformed

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        // TODO add your handling code here:
        Order order = new Order();
        setVisible(false);
        dispose();
        order.setVisible(true);
    }//GEN-LAST:event_orderBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to log out", "Select", JOptionPane.YES_NO_CANCEL_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        // TODO add your handling code here:
        Product product = new Product();
        setVisible(false);
        dispose();
        product.setVisible(true);
    }//GEN-LAST:event_productBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            String name = namefield.getText();
            String phone = phonefield.getText();
            String email = emailfield.getText();
            String address = addressfield.getText();
            String status = (String) statusbox.getSelectedItem();
            char[] ch = passwordfield.getPassword();
            String password = new String(ch);

            try {
                String query2 = "INSERT into appuser(userRole,name,mobileNumber,email,password,address,status) VALUES('Admin',?,?,?,?,?,?)";
                PreparedStatement ps = con.prepareStatement(query2);
                ps.setString(1, name);
                ps.setString(2, phone);
                ps.setString(3, email);
                ps.setString(4, password);
                ps.setString(5, address);
                ps.setString(6, status);

                int i = ps.executeUpdate();
                if (i > 0) {
                    JOptionPane.showMessageDialog(null, name + " added successfully");
//                    this.dispose();
//                    new UserManager().setVisible(true);
                    addItemInTable(phone, email);
                } else {
                    JOptionPane.showMessageDialog(null, name + " not added");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Fill all fields");
        }
        resetFields();
    }//GEN-LAST:event_saveBtnActionPerformed

    //update the data in the database
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if (validateForm()) {
            int index = userTable.getSelectedRow();
            TableModel model = userTable.getModel();

            String name = namefield.getText();
            String phone = phonefield.getText();
            String email = emailfield.getText();
            String address = addressfield.getText();
            String status = (String) statusbox.getSelectedItem();
            char[] ch = passwordfield.getPassword();
            String password = new String(ch);

            String id = model.getValueAt(index, 0).toString();
            appuserPk = Integer.parseInt(id);

            try {
                String query2 = "UPDATE appuser set name=?,mobileNumber=?,email=?,password=?,address=?,status=? WHERE appuser_pk=?";
                PreparedStatement ps = con.prepareStatement(query2);
                ps.setString(1, name);
                ps.setString(2, phone);
                ps.setString(3, email);
                ps.setString(4, password);
                ps.setString(5, address);
                ps.setString(6, status);
                ps.setInt(7, appuserPk);

                int i = ps.executeUpdate();
                if (i > 0) {
                    JOptionPane.showMessageDialog(null, name + " Updated sucessfully");
//                    this.dispose();
//                    new UserManager().setVisible(true);
                    rowIndex = userTable.getSelectedRow();
                    updateTable(rowIndex, appuserPk);
                } else {
                    JOptionPane.showMessageDialog(null, name + " not Updated");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fill all fields");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        namefield.setText("");
        passwordfield.setText("");
        phonefield.setText("");
        emailfield.setText("");
        addressfield.setText("");
        statusbox.setSelectedItem("Active");
        updateBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
        saveBtn.setEnabled(true);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:new ManageUser().setVisible(true);
    }//GEN-LAST:event_emailfieldActionPerformed

    private void phonefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonefieldActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    //getting table data in the input field for editing/updating
    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        // TODO add your handling code here:
        int index = userTable.getSelectedRow();
        TableModel model = userTable.getModel();

        String id = model.getValueAt(index, 0).toString();
        appuserPk = Integer.parseInt(id);

        String name = model.getValueAt(index, 1).toString();
        namefield.setText(name);

        String phone = model.getValueAt(index, 2).toString();
        phonefield.setText(phone);

        String email = model.getValueAt(index, 3).toString();
        emailfield.setText(email);

        String address = model.getValueAt(index, 4).toString();
        addressfield.setText(address);

        String status = model.getValueAt(index, 5).toString();
        statusbox.removeAllItems();
        if (status.equals("Active")) {
            statusbox.addItem("Active");
            statusbox.addItem("InActive");
        } else {
            statusbox.addItem("InActive");
            statusbox.addItem("Active");
        }
        saveBtn.setEnabled(false);
        updateBtn.setEnabled(true);
        deleteBtn.setEnabled(true);

        String password = model.getValueAt(index, 6).toString();
        passwordfield.setText(password);
    }//GEN-LAST:event_userTableMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:   

        // loading table for first time when app opens
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();

        try {
            String query1 = "SELECT * FROM appuser WHERE userRole = 'Admin'";
            PreparedStatement ps = con.prepareStatement(query1);
            ResultSet set = ps.executeQuery(query1);

            while (set.next()) {
                model.addRow(new Object[]{set.getString("appuser_pk"), set.getString("name"), set.getString("mobileNumber"), set.getString("email"), set.getString("address"), set.getString("status"), set.getString("password")});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        updateBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        rowIndex = userTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();

        //getting appuserPk value
        String id = model.getValueAt(rowIndex, 0).toString();
        appuserPk = Integer.parseInt(id);

        if (rowIndex >= 0) {
            JOptionPane.showConfirmDialog(null, "Do you want to delete ID " + appuserPk);
            try {
                String query = "DELETE FROM appuser WHERE appuser_pk = ?";
                PreparedStatement ps = con.prepareStatement(query);
                ps.setInt(1, appuserPk);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, appuserPk + " ID Deleted sucessfully");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            model.removeRow(rowIndex);
        }
        resetFields();
        updateBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
        saveBtn.setEnabled(true);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void catagoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catagoryBtnActionPerformed
        // TODO add your handling code here:
        Catagory catagory = new Catagory();
        setVisible(false);
        dispose();
        catagory.setVisible(true);

    }//GEN-LAST:event_catagoryBtnActionPerformed

    //add items in the display table on screen
    private void addItemInTable(String phone, String email) {
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();

        // Ensure connection object is valid
        if (con == null) {
            JOptionPane.showMessageDialog(null, "Database connection is not initialized.");
            return;
        }

        try {
            // Use a parameterized query to prevent SQL injection
            String query1 = "SELECT * FROM appuser WHERE mobileNumber = ? AND email = ?";
            PreparedStatement ps = con.prepareStatement(query1);
            ps.setString(1, phone);
            ps.setString(2, email);

            ResultSet set = ps.executeQuery();

            // Iterate through the result set
            while (set.next()) {
                // Add each row to the table
                model.addRow(new Object[]{
                    set.getInt("appuser_pk"), // Primary key
                    set.getString("name"), // Name
                    set.getString("mobileNumber"), // Mobile Number
                    set.getString("email"), // Email
                    set.getString("address"), // Address
                    set.getString("status"), // Status
                    set.getString("password") // Password
                });
            }

        } catch (Exception e) {
            // Show the error in a dialog box
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    //update table on the display
    private void updateTable(int rowIndex, int appuserPk) {
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();

        // Ensure the database connection is valid
        if (con == null) {
            JOptionPane.showMessageDialog(null, "Database connection is not initialized.");
            return;
        }

        try {
            // Use a parameterized query to get data
            String query1 = "SELECT * FROM appuser WHERE appuser_pk = ?";
            PreparedStatement ps = con.prepareStatement(query1);
            ps.setInt(1, appuserPk);
            ResultSet set = ps.executeQuery();

            // Check if the result set has data
            if (set.next()) {
                // Update the table row
                model.setValueAt(set.getInt("appuser_pk"), rowIndex, 0); // Column index adjusted to start from 0
                model.setValueAt(set.getString("name"), rowIndex, 1);
                model.setValueAt(set.getString("mobileNumber"), rowIndex, 2);
                model.setValueAt(set.getString("email"), rowIndex, 3);
                model.setValueAt(set.getString("address"), rowIndex, 4);
                model.setValueAt(set.getString("status"), rowIndex, 5);
                model.setValueAt(set.getString("password"), rowIndex, 6);
            } else {
                JOptionPane.showMessageDialog(null, "No data found for appuser_pk: " + appuserPk);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error updating table: " + e.getMessage());
        }

        resetFields();
        // Optionally disable the button
        updateBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
    }

    private void resetFields() {
        namefield.setText("");
        passwordfield.setText("");
        phonefield.setText("");
        emailfield.setText("");
        addressfield.setText("");
        statusbox.setSelectedItem("Active");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressfield;
    private javax.swing.JButton catagoryBtn;
    private javax.swing.JButton customerBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JTextField namefield;
    private javax.swing.JButton orderBtn;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JTextField phonefield;
    private javax.swing.JButton productBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<String> statusbox;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton userBtn;
    private javax.swing.JTable userTable;
    private javax.swing.JButton viewOrderBtn;
    // End of variables declaration//GEN-END:variables

//getting connection
    Connection con = Conn.getCon();

    private int appuserPk = 0;

    int rowIndex = 0;
}
